apiVersion: v1
kind: Service
metadata:
  name: monica-mariadb
  namespace: monicahq
spec:
  clusterIP: None   # headless for StatefulSet
  ports:
  - port: 3306
    targetPort: 3306
  selector: {app: monica-mariadb}
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: monica-mariadb
  namespace: monicahq
spec:
  serviceName: monica-mariadb
  replicas: 1
  selector:
    matchLabels: {app: monica-mariadb}
  template:
    metadata:
      labels: {app: monica-mariadb}
    spec:
      containers:
      - name: db
        image: mariadb:11
        envFrom:
        - secretRef:
            name: monica-secrets
        env:
        - name: MYSQL_DATABASE
          value: monica
        - name: MYSQL_USER
          value: monica
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: monica-secrets
              key: DB_PASSWORD
        ports: [{containerPort: 3306}]
        volumeMounts:
        - name: data
          mountPath: /var/lib/mysql
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: monica-db
