apiVersion: v1
kind: ConfigMap
metadata:
  name: stirling-env
  namespace: stirling-pdf
data:
  TZ: "Europe/Rome"
  DOCKER_ENABLE_SECURITY: "false"   # flip to true & add auth if exposing publicly
  # Add OCR_LANGS, WORKER_THREADS, etc. per docs
