apiVersion: apps/v1
kind: Deployment
metadata:
  name: stirling-pdf
  namespace: stirling-pdf
spec:
  template:
    spec:
      containers:
      - name: web
        envFrom:
        - configMapRef:
            name: stirling-env
        - secretRef:
            name: stirling-oauth-secret
