apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pdf-cache
  namespace: stirling-pdf
spec:
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: 5Gi
  storageClassName: local-path    # k3s default
