apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monicahq
  namespace: argocd
spec:
  source:
    repoURL: https://github.com/syscall00/declarative-cluster.git
    targetRevision: HEAD
    path: apps/monicahq/base
  destination:
    server: https://kubernetes.default.svc
    namespace: monicahq
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
