apiVersion: v1
kind: ConfigMap
metadata:
  name: litellm-config
  namespace: litellm-proxy
data:
  config.yaml: |
    model_list:
      - model_name: gpt-3.5-turbo
        litellm_params:
          model: openai/gpt-3.5-turbo
          api_base: http://192.168.1.2:1234
