apiVersion: v1
kind: Service
metadata:
  name: litellm-db
  namespace: litellm-proxy
spec:
  clusterIP: None
  ports:
  - port: 5432
    targetPort: 5432
  selector:
    app: litellm-db
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: litellm-db
  namespace: litellm-proxy
spec:
  serviceName: litellm-db
  replicas: 1
  selector:
    matchLabels:
      app: litellm-db
  template:
    metadata:
      labels:
        app: litellm-db
    spec:
      containers:
      - name: db
        image: postgres:16
        env:
        - name: POSTGRES_DB
          value: litellm
        - name: POSTGRES_USER
          value: litellm
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: litellm-proxy-env
              key: POSTGRES_PASSWORD
        ports:
        - containerPort: 5432
        volumeMounts:
        - name: data
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: litellm-db
