resources:
  - namespace.yaml
  - configmap.yaml
  - secret.yaml
  - db.yaml
  - pvc.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
