apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: litellm-db
  namespace: litellm-proxy
spec:
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: 5Gi
  storageClassName: local-path
