apiVersion: v1
kind: Secret
metadata:
  name: litellm-proxy-env
  namespace: litellm-proxy
stringData:
  LITELLM_MASTER_KEY: "sk-1234"
  LITELLM_SALT_KEY: "sk-XXXXXXXX"
  DATABASE_URL: "postgres://litellm:changeme@litellm-db:5432/litellm"
  POSTGRES_PASSWORD: "changeme"
  PORT: "4000"
  STORE_MODEL_IN_DB: "True"
