apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: adventurelog-db
  namespace: adventurelog
spec:
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: 10Gi
  storageClassName: local-path
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: adventurelog-media
  namespace: adventurelog
spec:
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: 5Gi
  storageClassName: local-path
