# apps/immich/base/postgres.yaml
apiVersion: v1
kind: Service
metadata:
  name: immich-postgres
  namespace: immich
spec:
  clusterIP: None
  ports: [{ port: 5432, targetPort: 5432 }]
  selector: { app: immich-postgres }
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: immich-postgres
  namespace: immich
spec:
  serviceName: immich-postgres
  replicas: 1
  selector: { matchLabels: { app: immich-postgres } }
  template:
    metadata: { labels: { app: immich-postgres } }
    spec:
      containers:
      - name: db
        image: postgres:15-alpine
        envFrom: [{ secretRef: { name: immich-secrets } }]
        env:
        - name: POSTGRES_DB
          value: immich
        ports: [{ containerPort: 5432 }]
        volumeMounts:
        - name: data
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: upload   # reuse fast local storage
