# apps/immich/base/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: immich
  namespace: immich
spec:
  ports:
  - port: 80
    targetPort: 3001
  selector: { app: immich-server }
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: immich
  namespace: immich
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-dns
spec:
  rules:
  - host: photos.infrazone.cc
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: immich
            port:
              number: 80
  tls:
  - hosts: [photos.infrazone.cc]
    secretName: immich-tls
