# apps/immich/base/upload-pvc.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: upload
  namespace: immich
spec:
  accessModes: [ReadWriteOnce]
  resources: { requests: { storage: 1Gi } }
  storageClassName: local-path
