---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-token
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgCP+bZzPMZNhurrduWqOepLO+UdafyxTVV4xRKEwwCXI/pnsXF97LAeWXAahurHVNGCZdlNdfFAqxF6NC1D2GvSwgumJKnvsgdBTfPHrOQNqAfxcLeQQvpwoKfmSryy2deatlm0a9a9ghORJ7Xol2XTzs82owKByC2Lxman/F6mpUORblItEDl7PtAek5YwoXfhSW+Vn17h75W6OVx0rAquwHwQh9stiaWsG4R7dC7ABp+wDP9KesabfZAPgPS819oT4GxdEWPlX2rD0RLP0ebllM+5MiG1C7hG1yGcSje7NspfEJTEexTAHYBs+B3zvbhyfzyX27hOX+oKvoer7vD6ZxTLqutkOzxQU+9EnDyvVY4A7+xvatyP6njUjtWjPnaslW5zPuBTmn71vpW9GpmIky/jPdZ5qVDXKaJPPnNA1MRWzYMdjqrnRnIaqf65AGBOtBNY0kglm2JWNthiwnVGOxXA9vUD7zJuAQMSIrbQUkbXXI82jCPqRE8AgDpcAah7ATSjti27zLfKUPHfHuPd3gPdtdgNRP9cF4hh2v3UIaCSdSmZvhhgEN1SV59bwnJKtUsKot+gzldPo0Z1ymZU4w3bIQQePrPIBPhaWRv0SpdX3HdeNiD+u4gTK+KgiZRAtAmHPA5B2zdfj75WtcRZz14H2mFqEhNzZf3vSnNUEYxHID7CLykSWSY2BnuHgDkDX1vGQgZu3ePz++tkkAXfOtX692WgJPQ58bZLzqKKN8f8Nqs/Sxwe
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-api-token
      namespace: cert-manager
